### ISSUE TITLE
normalize() maybe wrong?

### ISSUE THREAD

**Issue by freedom12** [nicklockwood/VectorMath#21] opened 2019-06-16 10:36 UTC
```
func normalized() -> Vector4 {
    let lengthSquared = self.lengthSquared
    if lengthSquared ~= 0 || lengthSquared ~= 1 {
        return self
    }
    return self / sqrt(lengthSquared)
}

```

should be " lengthSquared == 0 || lengthSquared == 1 "

**Comment by nicklockwood** [comment] 2019-06-16 11:43
Why?

**Comment by nicklockwood** [comment] 2019-06-16 11:47
Oh, hmm I see. I think the problem is really that the value of epsilon is way too large. Should probably much closer to the actual limit of float precision.

**Comment by nicklockwood** [comment] 2019-11-10 08:18
Fixed in 0.4.1

**Closed by nicklockwood** 2019-11-10 08:18 UTC
